version: '2.3'
services:

  connect:
    hostname: connect
    image: ghcr.io/rstudio/rstudio-connect:bionic-${RSC_VERSION}
    scale: 2
    ports:
      - 3939
    privileged: true
    volumes:
      - "${RSC_LICENSE_FILE}:/var/lib/rstudio-connect/license.lic"
    platform: linux/amd64
