# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: lint

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: local::., any::lintr, any::devtools, any::testthat
          needs: lint

      - name: Lint
        shell: Rscript {0}
        run: |
          Sys.setlocale(locale = "C")
          devtools::load_all() # helps with object usage linter

          package_lints <- devtools::lint(cache = FALSE)

          # Assert that there are no lint errors
          if (length(package_lints) > 0) print(package_lints)
          testthat::expect_length(package_lints, 0)
